version: '3.4'

networks:
  backend:

services:
  epa-database:
    container_name: epa-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd121#
    networks:
      - backend
    ports:
      - 8001:1433 
  epa-webapi:
    container_name: epa-web-api
    image: mykhailodock/epawebapi:1.00
    build:
      context: .
      dockerfile: EPA-WebAPI/Dockerfile
    networks:
      - backend
    ports:
      - 8002:80 
    environment:
      - DB_HOST=epa-database
      - DB_NAME=epa.main-db
      - MSSQL_SA_PASSWORD=P@ssw0rd121#